name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.14, 1.15, 1.16]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Set build variables
        run: |
          echo "GOPROXY=https://proxy.golang.org" >> $GITHUB_ENV
          echo "GO111MODULE=on" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: go get -v golang.org/x/lint/golint

      - name: Run Tests
        run: |
          golint -set_exit_status ./...
          go test -race ./internal/... ./pkg/...